import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
const db = new PrismaClient();
const passwordDigest = await bcrypt.hash("spike-password", 12);
const organization = await db.organization.upsert({ where: { key: "spike-shop" }, update: {}, create: { key: "spike-shop", name: "Spike Bike Shop", timezone: "America/Chicago" } });
const manager = await db.user.upsert({ where: { login: "manager" }, update: { passwordDigest, platformAdministrator: true }, create: { login: "manager", email: "manager@example.test", name: "Spike Manager", passwordDigest, passwordChangeRequired: false, platformAdministrator: true } });
await db.organizationMembership.upsert({ where: { organizationId_userId: { organizationId: organization.id, userId: manager.id } }, update: {}, create: { organizationId: organization.id, userId: manager.id, role: "manager" } });
const ada = await db.person.upsert({ where: { id: 900001n }, update: {}, create: { id: 900001n, organizationId: organization.id, firstName: "Ada", lastName: "Rider", displayName: "Ada Rider", normalizedEmail: "ada@example.test", email: "ada@example.test" } });
const otherOrganization = await db.organization.upsert({ where: { key: "other-bike-shop" }, update: {}, create: { key: "other-bike-shop", name: "Other Bike Shop", timezone: "America/New_York" } });
const otherManager = await db.user.upsert({ where: { login: "other-manager" }, update: { passwordDigest }, create: { login: "other-manager", email: "other-manager@example.test", name: "Other Manager", passwordDigest, passwordChangeRequired: false } });
await db.organizationMembership.upsert({ where: { organizationId_userId: { organizationId: otherOrganization.id, userId: otherManager.id } }, update: {}, create: { organizationId: otherOrganization.id, userId: otherManager.id, role: "manager" } });
const blair = await db.person.upsert({ where: { id: 900101n }, update: {}, create: { id: 900101n, organizationId: otherOrganization.id, firstName: "Blair", lastName: "Other", displayName: "Blair Other", normalizedEmail: "blair@example.test", email: "blair@example.test" } });
const spikeCommunity = await db.tag.upsert({ where: { organizationId_name: { organizationId: organization.id, name: "Community" } }, update: {}, create: { organizationId: organization.id, name: "Community" } });
const otherCommunity = await db.tag.upsert({ where: { organizationId_name: { organizationId: otherOrganization.id, name: "Community" } }, update: {}, create: { organizationId: otherOrganization.id, name: "Community" } });
await db.personTag.createMany({ data: [{ organizationId: organization.id, personId: ada.id, tagId: spikeCommunity.id }, { organizationId: otherOrganization.id, personId: blair.id, tagId: otherCommunity.id }], skipDuplicates: true });
console.log("seeded manager / spike-password (Spike Bike Shop) and other-manager / spike-password (Other Bike Shop)");
await db.$disconnect();
