services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: horcrux
      MYSQL_DATABASE: freehub_development
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password", "horcrux"]
      timeout: 20s
      retries: 10
    networks:
      - freehub_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: horcrux
      RAILS_ENV: development
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - "3000:3000"
    # depends_on:
    #   db:
    #     condition: service_healthy
    volumes:
      - .:/workspace
    command: sleep infinity  # This will keep the container running
    networks:
      - freehub_network

networks:
  freehub_network:
    name: freehub_network

volumes:
  db_data: