source "https://rubygems.org"
gem "rails", "~> 8.1.0"
gem "pg", "~> 1.6"
gem "puma", ">= 6.0"
gem "bcrypt", "~> 3.1"
gem "turbo-rails"
gem "importmap-rails"

group :development, :test do
  gem "minitest"
end
