import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import "./style.css";

type Person = { id: string; displayName: string; staff: boolean };
let csrfToken = "";
const request = async <T,>(path: string, options?: RequestInit): Promise<T> => { const response = await fetch(path, { ...options, headers: { "content-type": "application/json", ...(csrfToken ? { "x-csrf-token": csrfToken } : {}), ...(options?.headers || {}) } }); if (!response.ok) { const payload = await response.json().catch(() => ({})) as { error?: string | { message?: string } }; throw new Error(typeof payload.error === "string" ? payload.error : payload.error?.message || "Request failed"); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; };
function Login() { const navigate = useNavigate(); const [login, setLogin] = useState("manager"); const [password, setPassword] = useState("spike-password"); const [error, setError] = useState(""); return <main><h1>Freehub</h1><form onSubmit={async (event) => { event.preventDefault(); try { const result = await request<{ organizationId: string; csrfToken: string; passwordChangeRequired: boolean }>("/api/login", { method: "POST", body: JSON.stringify({ login, password }) }); csrfToken = result.csrfToken; navigate(result.passwordChangeRequired ? "/change-password" : `/organizations/${result.organizationId}`); } catch (err) { setError((err as Error).message); } }}><label>Login<input value={login} onChange={(event) => setLogin(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button>Log in</button>{error && <p role="alert">{error}</p>}</form></main>; }
function ChangePassword() { const navigate = useNavigate(); const [password, setPassword] = useState(""); const [error, setError] = useState(""); return <main><h1>Change your temporary password</h1><form onSubmit={async (event) => { event.preventDefault(); try { await request("/api/password", { method: "POST", body: JSON.stringify({ password }) }); const organizations = await request<{ id: string }[]>("/api/organizations"); navigate(`/organizations/${organizations[0].id}`); } catch (err) { setError((err as Error).message); } }}><label>New password<input type="password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} /></label><button>Save password</button>{error && <p role="alert">{error}</p>}</form></main>; }
function People() { const { organizationId = "" } = useParams(); const [query, setQuery] = useState("Ada"); const [people, setPeople] = useState<Person[]>([]); const [error, setError] = useState(""); useEffect(() => { if (query.length < 2) return; request<Person[]>(`/api/organizations/${organizationId}/people?q=${encodeURIComponent(query)}`).then(setPeople).catch((err) => setError(err.message)); }, [organizationId, query]); return <main><nav><Link to={`/organizations/${organizationId}`}>People</Link> <a href={`/api/organizations/${organizationId}/reports/people.csv`}>Export CSV</a></nav><h1>People</h1><label>Search<input aria-label="Search people" value={query} onChange={(event) => setQuery(event.target.value)} /></label>{error && <p role="alert">{error}</p>}<ul>{people.map((person) => <li key={person.id}><Link to={`/organizations/${organizationId}/people/${person.id}`}>{person.displayName}</Link>{person.staff ? " (Staff)" : ""}</li>)}</ul></main>; }
function Profile() { const { organizationId = "", personId = "" } = useParams(); const [person, setPerson] = useState<{ displayName: string; id: string } | null>(null); useEffect(() => { request<{ displayName: string; id: string }>(`/api/organizations/${organizationId}/people/${personId}`).then(setPerson).catch(() => setPerson(null)); }, [organizationId, personId]); return <main><Link to={`/organizations/${organizationId}`}>People</Link>{person ? <><h1>{person.displayName}</h1><button onClick={() => request(`/api/organizations/${organizationId}/visits`, { method: "POST", body: JSON.stringify({ personId, activity: "project", arrivedAt: new Date().toISOString() }) })}>Sign in for project</button></> : <p>Person not found</p>}</main>; }
function App() { return <Routes><Route path="/" element={<Login />} /><Route path="/change-password" element={<ChangePassword />} /><Route path="/organizations/:organizationId" element={<People />} /><Route path="/organizations/:organizationId/people/:personId" element={<Profile />} /></Routes>; }
createRoot(document.getElementById("root")!).render(<BrowserRouter><App /></BrowserRouter>);
