CREATE TYPE "OrganizationRole" AS ENUM ('manager', 'operator');
CREATE TYPE "ServiceType" AS ENUM ('membership', 'earn_a_bike', 'class_');
CREATE TYPE "VisitActivity" AS ENUM ('project', 'volunteering');
CREATE TYPE "MigrationIssueDisposition" AS ENUM ('open', 'accepted', 'resolved', 'quarantined');

CREATE TABLE "Organization" ("id" BIGSERIAL PRIMARY KEY, "name" VARCHAR(80) NOT NULL, "key" VARCHAR(40) NOT NULL, "timezone" VARCHAR(64) NOT NULL, "location" VARCHAR(255), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "User" ("id" BIGSERIAL PRIMARY KEY, "login" VARCHAR(80) NOT NULL, "email" VARCHAR(320) NOT NULL, "name" VARCHAR(160) NOT NULL, "passwordDigest" VARCHAR(255) NOT NULL, "passwordChangeRequired" BOOLEAN NOT NULL DEFAULT true, "platformAdministrator" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "OrganizationMembership" ("id" BIGSERIAL PRIMARY KEY, "organizationId" BIGINT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "userId" BIGINT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "role" "OrganizationRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("organizationId", "userId"));
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY, "userId" BIGINT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "organizationId" BIGINT REFERENCES "Organization"("id") ON DELETE SET NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Person" ("id" BIGSERIAL PRIMARY KEY, "organizationId" BIGINT NOT NULL REFERENCES "Organization"("id"), "firstName" VARCHAR(120) NOT NULL, "lastName" VARCHAR(120), "displayName" VARCHAR(255) NOT NULL, "email" VARCHAR(320), "normalizedEmail" VARCHAR(320), "phone" VARCHAR(80), "normalizedPhone" VARCHAR(32), "staff" BOOLEAN NOT NULL DEFAULT false, "archivedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Visit" ("id" BIGSERIAL PRIMARY KEY, "organizationId" BIGINT NOT NULL REFERENCES "Organization"("id"), "personId" BIGINT NOT NULL REFERENCES "Person"("id"), "activity" "VisitActivity" NOT NULL, "arrivedAt" TIMESTAMP(3), "startedAt" TIMESTAMP(3), "endedAt" TIMESTAMP(3), "durationSeconds" INTEGER, "staffSnapshot" BOOLEAN NOT NULL, "memberSnapshot" BOOLEAN NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "visit_nonnegative_duration" CHECK ("durationSeconds" IS NULL OR "durationSeconds" >= 0), CONSTRAINT "visit_end_not_before_start" CHECK ("endedAt" IS NULL OR "startedAt" IS NULL OR "endedAt" >= "startedAt"));
CREATE TABLE "Service" ("id" BIGSERIAL PRIMARY KEY, "organizationId" BIGINT NOT NULL REFERENCES "Organization"("id"), "personId" BIGINT NOT NULL REFERENCES "Person"("id"), "type" "ServiceType" NOT NULL, "startDate" DATE, "endDate" DATE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "service_inclusive_dates" CHECK ("endDate" IS NULL OR "startDate" IS NULL OR "endDate" >= "startDate"));
CREATE TABLE "MigrationRun" ("id" BIGSERIAL PRIMARY KEY, "sourceSha256" CHAR(64) NOT NULL, "contractVersion" INTEGER NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "reportSha256" CHAR(64));
CREATE TABLE "MigrationIssue" ("id" BIGSERIAL PRIMARY KEY, "migrationRunId" BIGINT NOT NULL REFERENCES "MigrationRun"("id") ON DELETE CASCADE, "sourceTable" VARCHAR(80) NOT NULL, "sourceId" BIGINT, "category" VARCHAR(120) NOT NULL, "disposition" "MigrationIssueDisposition" NOT NULL DEFAULT 'open', "payloadFingerprint" CHAR(64) NOT NULL, "sanitizedDetail" JSONB NOT NULL, UNIQUE("migrationRunId", "sourceTable", "sourceId", "category"));
CREATE TABLE "LegacyIdentity" ("id" BIGSERIAL PRIMARY KEY, "migrationRunId" BIGINT NOT NULL REFERENCES "MigrationRun"("id") ON DELETE CASCADE, "sourceTable" VARCHAR(80) NOT NULL, "sourceId" BIGINT NOT NULL, "targetEntity" VARCHAR(80) NOT NULL, "targetId" BIGINT NOT NULL, UNIQUE("migrationRunId", "sourceTable", "sourceId", "targetEntity", "targetId"));

CREATE UNIQUE INDEX "organizations_key_lower_unique" ON "Organization" (lower("key"));
CREATE UNIQUE INDEX "users_login_lower_unique" ON "User" (lower("login"));
CREATE UNIQUE INDEX "users_email_lower_unique" ON "User" (lower("email"));
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Person_organizationId_normalizedEmail_idx" ON "Person"("organizationId", "normalizedEmail");
CREATE INDEX "Person_organizationId_normalizedPhone_idx" ON "Person"("organizationId", "normalizedPhone");
CREATE INDEX "Person_organizationId_displayName_idx" ON "Person"("organizationId", "displayName");
CREATE INDEX "Visit_organizationId_arrivedAt_idx" ON "Visit"("organizationId", "arrivedAt");
