import { Type } from "@sinclair/typebox";

export const LoginBody = Type.Object({ login: Type.String({ minLength: 1 }), password: Type.String({ minLength: 1 }) });
export const PasswordBody = Type.Object({ password: Type.String({ minLength: 12, maxLength: 255 }) });
export const UserParams = Type.Object({ userId: Type.String({ pattern: "^[0-9]+$" }) });
export const OrganizationBody = Type.Object({ name: Type.String({ minLength: 1, maxLength: 80 }), key: Type.String({ minLength: 2, maxLength: 40, pattern: "^[a-z0-9-]+$" }), timezone: Type.String({ minLength: 1, maxLength: 64 }), location: Type.Optional(Type.String({ maxLength: 255 })), managerUserId: Type.String({ pattern: "^[0-9]+$" }) });
export const OrganizationSettingsBody = Type.Object({ name: Type.String({ minLength: 1, maxLength: 80 }), timezone: Type.String({ minLength: 1, maxLength: 64 }), location: Type.Optional(Type.String({ maxLength: 255 })) });
export const MembershipBody = Type.Object({ userId: Type.String({ pattern: "^[0-9]+$" }), role: Type.Union([Type.Literal("manager"), Type.Literal("operator")]), startsAt: Type.Optional(Type.String({ format: "date" })), endsAt: Type.Optional(Type.Union([Type.String({ format: "date" }), Type.Null()])) });
export const MembershipUpdateBody = Type.Object({ role: Type.Union([Type.Literal("manager"), Type.Literal("operator")]), startsAt: Type.String({ format: "date" }), endsAt: Type.Optional(Type.Union([Type.String({ format: "date" }), Type.Null()])) });
export const UserSettingsBody = Type.Object({ name: Type.String({ minLength: 1, maxLength: 160 }), email: Type.String({ format: "email", maxLength: 320 }) });
export const ProvisionUserBody = Type.Object({ login: Type.String({ minLength: 2, maxLength: 80 }), name: Type.String({ minLength: 1, maxLength: 160 }), email: Type.String({ format: "email", maxLength: 320 }) });
export const OrganizationParams = Type.Object({ organizationId: Type.String({ pattern: "^[0-9]+$" }) });
export const MembershipParams = Type.Intersect([OrganizationParams, UserParams]);
export const PersonParams = Type.Intersect([OrganizationParams, Type.Object({ personId: Type.String({ pattern: "^[0-9]+$" }) })]);
export const TagParams = Type.Intersect([OrganizationParams, Type.Object({ tagId: Type.String({ pattern: "^[0-9]+$" }) })]);
export const PersonTagParams = Type.Intersect([PersonParams, Type.Object({ tagId: Type.String({ pattern: "^[0-9]+$" }) })]);
export const NoteParams = Type.Intersect([OrganizationParams, Type.Object({ noteId: Type.String({ pattern: "^[0-9]+$" }) })]);
export const PersonBody = Type.Object({ firstName: Type.String({ minLength: 1, maxLength: 120 }), lastName: Type.Optional(Type.Union([Type.String({ maxLength: 120 }), Type.Null()])), email: Type.Optional(Type.Union([Type.String({ maxLength: 320 }), Type.Null()])), phone: Type.Optional(Type.Union([Type.String({ maxLength: 80 }), Type.Null()])), street1: Type.Optional(Type.Union([Type.String({ maxLength: 255 }), Type.Null()])), street2: Type.Optional(Type.Union([Type.String({ maxLength: 255 }), Type.Null()])), city: Type.Optional(Type.Union([Type.String({ maxLength: 120 }), Type.Null()])), state: Type.Optional(Type.Union([Type.String({ maxLength: 120 }), Type.Null()])), postalCode: Type.Optional(Type.Union([Type.String({ maxLength: 40 }), Type.Null()])), country: Type.Optional(Type.Union([Type.String({ maxLength: 8 }), Type.Null()])), yearOfBirth: Type.Optional(Type.Union([Type.Integer({ minimum: 1880, maximum: 2100 }), Type.Null()])), staff: Type.Optional(Type.Boolean()), emailOptOut: Type.Optional(Type.Boolean()) });
export const SearchQuery = Type.Object({ q: Type.String({ minLength: 2, maxLength: 120 }) });
export const VisitBody = Type.Object({ personId: Type.String({ pattern: "^[0-9]+$" }), activity: Type.Union([Type.Literal("project"), Type.Literal("volunteering")]), arrivedAt: Type.String({ format: "date-time" }) });
export const VisitParams = Type.Intersect([OrganizationParams, Type.Object({ visitId: Type.String({ pattern: "^[0-9]+$" }) })]);
export const TagAssignmentBody = Type.Object({ names: Type.Array(Type.String({ minLength: 1, maxLength: 120 }), { maxItems: 50 }) });
export const NoteBody = Type.Object({ text: Type.String({ minLength: 1, maxLength: 20_000 }), personId: Type.Optional(Type.String({ pattern: "^[0-9]+$" })), visitId: Type.Optional(Type.String({ pattern: "^[0-9]+$" })), serviceId: Type.Optional(Type.String({ pattern: "^[0-9]+$" })) });
export const NoteUpdateBody = Type.Object({ text: Type.String({ minLength: 1, maxLength: 20_000 }) });
